# Generated by Django 5.2.4 on 2025-07-09 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landowner_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('workers_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manager_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('investor_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('platform_share', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('distribution_date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farming.farmingproject')),
            ],
        ),
    ]
