# Generated by Django 5.1.4 on 2025-07-19 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Permission Categories',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('FORUM_MANAGEMENT', 'Forum Management'), ('USER_MANAGEMENT', 'User Management'), ('LAND_APPROVAL', 'Land Approval'), ('PROJECT_APPROVAL', 'Project Approval'), ('CONTENT_MODERATION', 'Content Moderation'), ('REPORT_MANAGEMENT', 'Report Management'), ('NOTIFICATION_MANAGEMENT', 'Notification Management'), ('ANALYTICS_ACCESS', 'Analytics Access'), ('CUSTOM', 'Custom Permission')], max_length=50)),
                ('permission_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('scope', models.CharField(blank=True, help_text='Specific scope of this permission (e.g., specific categories, user types)', max_length=200)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=True)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_reject', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_permissions.permissioncategory')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Permissions',
                'unique_together': {('user', 'permission_type', 'permission_name')},
            },
        ),
        migrations.CreateModel(
            name='PermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GRANTED', 'Permission Granted'), ('REVOKED', 'Permission Revoked'), ('USED', 'Permission Used'), ('EXPIRED', 'Permission Expired'), ('MODIFIED', 'Permission Modified')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_actions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='user_permissions.userpermission')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
