# Generated by Django 5.2.4 on 2025-07-09 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('lands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('HARVESTED', 'Harvested'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=20)),
                ('crops', models.CharField(max_length=200)),
                ('estimated_yield', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.land')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='accounts.user')),
                ('workers', models.ManyToManyField(related_name='farming_projects', to='accounts.user')),
            ],
        ),
    ]
