# Generated by Django 5.2.4 on 2025-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_supervisor_activitylog_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
