# Generated by Django 5.1.4 on 2025-07-15 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('APPROVE_LAND', 'Approve Land'), ('REJECT_LAND', 'Reject Land'), ('APPROVE_PROJECT', 'Approve Project'), ('REJECT_PROJECT', 'Reject Project'), ('DELETE_LAND', 'Delete Land'), ('DELETE_PROJECT', 'Delete Project'), ('DELETE_USER', 'Delete User'), ('DELETE_LISTING', 'Delete Listing'), ('DELETE_RECOMMENDATION', 'Delete Recommendation'), ('EDIT_LAND', 'Edit Land'), ('EDIT_PROJECT', 'Edit Project'), ('BULK_APPROVE_LANDS', 'Bulk Approve Lands'), ('BULK_REJECT_LANDS', 'Bulk Reject Lands'), ('BULK_APPROVE_PROJECTS', 'Bulk Approve Projects'), ('BULK_REJECT_PROJECTS', 'Bulk Reject Projects')], max_length=30)),
                ('target_object_type', models.CharField(max_length=50)),
                ('target_object_id', models.IntegerField()),
                ('target_object_name', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
