# Generated by Django 5.2.4 on 2025-07-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_adminauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LAND_PENDING', 'Land Pending Approval'), ('PROJECT_PENDING', 'Project Pending Approval'), ('LAND_APPROVED', 'Land Approved'), ('LAND_REJECTED', 'Land Rejected'), ('PROJECT_APPROVED', 'Project Approved'), ('PROJECT_REJECTED', 'Project Rejected'), ('NEW_USER', 'New User Registration'), ('NEW_RECOMMENDATION', 'New Recommendation'), ('ACTIVITY_CONFIRMED', 'Activity Confirmed'), ('ACTIVITY_DISAPPROVED', 'Activity Disapproved'), ('NEW_ACTIVITY', 'New Activity Logged'), ('NEW_UPLOAD', 'New Image Upload'), ('PROJECT_UPDATE', 'Project Status Update'), ('TEAM_MESSAGE', 'Team Message'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('WEATHER_ALERT', 'Weather Alert'), ('EQUIPMENT_ISSUE', 'Equipment Issue'), ('MARKETPLACE_ORDER', 'Marketplace Order'), ('PAYMENT_RECEIVED', 'Payment Received'), ('SYSTEM_MAINTENANCE', 'System Maintenance')], max_length=20),
        ),
    ]
