# Generated by Django 5.1.4 on 2025-08-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_frequency',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('HOURLY', 'Hourly Digest'), ('DAILY', 'Daily Digest'), ('WEEKLY', 'Weekly Digest')], default='IMMEDIATE', help_text='How often to receive notifications', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_sound',
            field=models.BooleanField(default=True, help_text='Play notification sounds'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Receive browser push notifications'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LAND_PENDING', 'Land Pending Approval'), ('PROJECT_PENDING', 'Project Pending Approval'), ('LAND_APPROVED', 'Land Approved'), ('LAND_REJECTED', 'Land Rejected'), ('PROJECT_APPROVED', 'Project Approved'), ('PROJECT_REJECTED', 'Project Rejected'), ('NEW_USER', 'New User Registration'), ('NEW_RECOMMENDATION', 'New Recommendation'), ('ACTIVITY_CONFIRMED', 'Activity Confirmed'), ('ACTIVITY_DISAPPROVED', 'Activity Disapproved'), ('NEW_ACTIVITY', 'New Activity Logged'), ('NEW_UPLOAD', 'New Image Upload'), ('PROJECT_UPDATE', 'Project Status Update'), ('TEAM_MESSAGE', 'Team Message'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_COMPLETED', 'Task Completed'), ('WEATHER_ALERT', 'Weather Alert'), ('EQUIPMENT_ISSUE', 'Equipment Issue'), ('MARKETPLACE_ORDER', 'Marketplace Order'), ('PAYMENT_RECEIVED', 'Payment Received'), ('SYSTEM_MAINTENANCE', 'System Maintenance'), ('TOPIC_REQUEST', 'Topic Request Submitted'), ('TOPIC_REQUEST_APPROVED', 'Topic Request Approved'), ('TOPIC_REQUEST_REJECTED', 'Topic Request Rejected'), ('TOPIC_REQUEST_UPDATED', 'Topic Request Updated'), ('NEW_TOPIC', 'New Topic Created'), ('NEW_REPLY', 'New Reply to Topic'), ('TOPIC_SUBSCRIPTION', 'Topic Subscription Update'), ('FORUM_MENTION', 'Forum Mention'), ('PERMISSION_GRANTED', 'Permission Granted'), ('PERMISSION_REVOKED', 'Permission Revoked'), ('PERMISSION_EXPIRED', 'Permission Expired'), ('ADMIN_ACTION', 'Admin Action Performed'), ('PROFILE_UPDATE', 'Profile Updated'), ('PASSWORD_CHANGE', 'Password Changed'), ('LOGIN_ALERT', 'Login Alert'), ('SECURITY_ALERT', 'Security Alert'), ('BACKUP_COMPLETE', 'Backup Complete'), ('SYSTEM_UPDATE', 'System Update')], max_length=30),
        ),
    ]
